// This is only the data thats being added to the Database

const categories = [
  {
    name: 'Skafferi',
    description: 'Basvaror: pasta, ris, tomater, kaffe och te',
  },
  {
    name: 'Drycker',
    description: 'Mineralvatten, läsk, juicer och mer',
  },
  {
    name: 'Snacks & godis',
    description: 'Chips, godis och nötter',
  },
  {
    name: 'Träning & vikt',
    description: 'Proteindrycker och bars för träning',
  },
  {
    name: 'Hygien & apotek',
    description: 'Hygien- och apoteksprodukter',
  },
  {
    name: 'Bröd, kex & kakor',
    description: 'God kex och kakor till kaffet',
  },
  {
    name: 'Barn & baby',
    description: 'Produkter för barn till bra priceer',
  },
  {
    name: 'Hem & Städ',
    description: 'Tvätt-, disk- och städprodukter',
  },
  {
    name: 'Husdjur',
    description: 'Mat, leksaker och tillbehör för husdjur',
  },
  {
    name: 'Fyndhörna',
    description: 'Hitta dina fynd här',
  }
  
];

const products = [
  {
    name: 'Gourmetpasta',
    description: 'Läcker gourmetpasta för pastaälskare',
    price: 19.99,
   image: 'https://picsum.photos/300/300',
    category_id: 1,
  },
  {
    name: 'Mineralvatten',
    description: 'Uppfriskande mineralvatten för hydrering',
    price: 15.99,
   image: 'https://picsum.photos/300/300',
    category_id: 2,
  },
  {
    name: 'Husdjursleksak',
    description: 'Interaktiv leksak för din pälsklädda vän',
    price: 79.99,
   image: 'https://picsum.photos/300/300',
    category_id: 9,
  },
  {
    name: 'Bok: Bästsäljare',
    description: 'En bästsäljande bok för bokälskare',
    price: 129.99,
   image: 'https://picsum.photos/300/300',
    category_id: 10,
  },
  {
    name: 'Shampo',
    description: 'Mild och vårdande schampo för alla hårtyper',
    price: 39.99,
   image: 'https://picsum.photos/300/300',
    category_id: 5,
  },
  {
    name: 'Proteindrink',
    description: 'Högkvalitativ proteindrink för träning',
    price: 29.99,
   image: 'https://picsum.photos/300/300',
    category_id: 4,
  },
  {
    name: 'Nötblandning',
    description: 'En utsökt blandning av nötter och torkad frukt',
    price: 29.99,
   image: 'https://picsum.photos/300/300',
    category_id: 3,
  },
  {
    name: 'Vitaminvatten',
    description: 'Hälsosamt vitaminberikat vatten',
    price: 29.99,
   image: 'https://picsum.photos/300/300',
    category_id: 2,
  },
  {
    name: 'Kaffe',
    description: 'Premiumkaffe från kända kaffebönor',
    price: 59.99,
   image: 'https://picsum.photos/300/300',
    category_id: 1,
  },
  {
    name: 'Tomatsås',
    description: 'Hemlagad tomatsås av hög kvalitet',
    price: 29.99,
   image: 'https://picsum.photos/300/300',
    category_id: 1,
  },
  {
    name: 'Energidryck',
    description: 'Energidryck med extra kick',
    price: 19.99,
   image: 'https://picsum.photos/300/300',
    category_id: 2,
  },
  {
    name: 'Chokladkakor',
    description: 'Mumsiga chokladkakor för sötsugna',
    price: 14.99,
   image: 'https://picsum.photos/300/300',
    category_id: 3,
  },
  {
    name: 'Vitamintillskott',
    description: 'Vitamintillskott för daglig hälsa',
    price: 29.99,
   image: 'https://picsum.photos/300/300',
    category_id: 4,
  },
  {
    name: 'Tvättmedel',
    description: 'Effektivt tvättmedel för rena kläder',
    price: 99.99,
   image: 'https://picsum.photos/300/300',
    category_id: 8,
  },
  {
    name: 'Risottoris',
    description: 'Premiumrisottoris för gourmetmatlagning',
    price: 59.99,
   image: 'https://picsum.photos/300/300',
    category_id: 1,
  },
  {
    name: 'Fruktjuice',
    description: 'Färskpressad fruktjuice för en hälsosam start på dagen',
    price: 33.99,
   image: 'https://picsum.photos/300/300',
    category_id: 2,
  },
  {
    name: 'Chips',
    description: 'Krispiga och smakrika chips för snacksätare',
    price: 24.99,
   image: 'https://picsum.photos/300/300',
    category_id: 3,
  },
  {
    name: 'Proteinbar',
    description: 'Proteinbar för snabb och bekväm energi',
    price: 19.99,
   image: 'https://picsum.photos/300/300',
    category_id: 4,
  },
  {
    name: 'Tandborste',
    description: 'Mjuk tandborste för daglig tandvård',
    price: 25.99,
   image: 'https://picsum.photos/300/300',
    category_id: 5,
  },
  {
    name: 'Hamburgare',
    description: 'Färdiga hamburgare för en enkel måltid',
    price: 49.99,
   image: 'https://picsum.photos/300/300',
    category_id: 6,
  },
  {
    name: 'Barnkläder',
    description: 'Söta barnkläder i olika storlekar och färger',
    price: 149.99,
   image: 'https://picsum.photos/300/300',
    category_id: 7,
  },
  {
    name: 'Diskmedel',
    description: 'Effektivt diskmedel för glänsande rena tallrikar',
    price: 39.99,
   image: 'https://picsum.photos/300/300',
    category_id: 8,
  },
  {
    name: 'Hundmat',
    description: 'Näringsrik hundmat för ditt fyrbenta sällskap',
    price: 69.99,
   image: 'https://picsum.photos/300/300',
    category_id: 9,
  },
  {
    name: 'Leksakspussel',
    description: 'Roligt leksakspussel för barn',
    price: 99.99,
   image: 'https://picsum.photos/300/300',
    category_id: 10,
  },  
  {
    name: 'Ekologiskt kaffe',
    description: 'Högkvalitativt ekologiskt kaffe från rättvis handel',
    price: 59.99,
   image: 'https://picsum.photos/300/300',
    category_id: 1,
  },
  {
    name: 'Läskedryck',
    description: 'Förfriskande läskedryck i olika smaker',
    price: 14.99,
   image: 'https://picsum.photos/300/300',
    category_id: 2,
  },
  {
    name: 'Popcorn',
    description: 'Krispiga popcorn för biokvällar',
    price: 20.99,
   image: 'https://picsum.photos/300/300',
    category_id: 3,
  },
  {
    name: 'Energibar',
    description: 'Energibar med naturliga ingredienser',
    price: 16.99,
   image: 'https://picsum.photos/300/300',
    category_id: 4,
  },
  {
    name: 'Tandtråd',
    description: 'Tandtråd för optimal tandvård',
    price: 19.99,
   image: 'https://picsum.photos/300/300',
    category_id: 5,
  },
  {
    name: 'Färskt bröd',
    description: 'Nybakat bröd för frukost och mellanmål',
    price: 9.99,
    image: 'https://picsum.photos/300/300',
    category_id: 6,
  },
  {
    name: 'Barnvagnar',
    description: 'Bekväma och säkra barnvagnar för småbarn',
    price: 1499.99,
    image: 'https://picsum.photos/300/300',
    category_id: 7,
  },
  {
    name: 'Badrumsrengöring',
    description: 'Effektiv rengöring för badrummet',
    price: 49.99,
    image: 'https://picsum.photos/300/300',
    category_id: 8,
  },
  {
    name: 'Kattmat',
    description: 'Smaklig kattmat för din kattkamrat',
    price: 49.99,
    image: 'https://picsum.photos/300/300',
    category_id: 9,
  },
  {
    name: 'Legosats',
    description: 'Kreativt legosats för barn och vuxna',
    price: 549.99,
    image: 'https://picsum.photos/300/300',
    category_id: 10,
  },
  {
    name: 'Olivolja',
    description: 'Kallpressad ekologisk olivolja',
    price: 89.99,
    image: 'https://picsum.photos/300/300',
    category_id: 1,
  },
  {
    name: 'Fruktsmoothie',
    description: 'Färsk fruktsmoothie för en hälsosam start på dagen',
    price: 49.99,
    image: 'https://picsum.photos/300/300',
    category_id: 2,
  },
  {
    name: 'Pretzel-snacks',
    description: 'Krispiga pretzel-snacks för knaprig njutning',
    price: 25.99,
    image: 'https://picsum.photos/300/300',
    category_id: 3,
  },
  {
    name: 'Vitaminpiller',
    description: 'Multivitamintillskott i pilleform',
    price: 69.99,
    image: 'https://picsum.photos/300/300',
    category_id: 4,
  },
  {
    name: 'Hårtork',
    description: 'Kraftfull hårtork för snabb styling',
    price: 599.99,
    image: 'https://picsum.photos/300/300',
    category_id: 5,
  },
  {
    name: 'Senap',
    description: 'Äkta senap gjord på ekologiska senapsfrön',
    price: 29.99,
    image: 'https://picsum.photos/300/300',
    category_id: 1,
  } 
];

module.exports = {
  products,
  categories,
};

