// This is only the data thats being added to the Database

const categories = [
  {
    name: 'Skafferi',
    description: 'Basvaror: pasta, ris, tomater, kaffe och te',
  },
  {
    name: 'Drycker',
    description: 'Mineralvatten, läsk, juicer och mer',
  },
  {
    name: 'Snacks & godis',
    description: 'Chips, godis och nötter',
  },
  {
    name: 'Träning & vikt',
    description: 'Proteindrycker och bars för träning',
  },
  {
    name: 'Hygien & apotek',
    description: 'Hygien- och apoteksprodukter',
  },
  {
    name: 'Bröd, kex & kakor',
    description: 'God kex och kakor till kaffet',
  },
  {
    name: 'Barn & baby',
    description: 'Produkter för barn till bra priceer',
  },
  {
    name: 'Hem & Städ',
    description: 'Tvätt-, disk- och städprodukter',
  },
  {
    name: 'Husdjur',
    description: 'Mat, leksaker och tillbehör för husdjur',
  },
  {
    name: 'Fyndhörna',
    description: 'Hitta dina fynd här',
  }
  
];

const products = [
  {
    name: 'Gourmetpasta',
    description: 'Läcker gourmetpasta för pastaälskare',
    price: 8.99,
    image: '/image/pasta.jpg',
    category_id: 1,
  },
  {
    name: 'Mineralvatten',
    description: 'Uppfriskande mineralvatten för hydrering',
    price: 1.49,
    image: '/image/mineralvatten.jpg',
    category_id: 2,
  },
  {
    name: 'Husdjursleksak',
    description: 'Interaktiv leksak för din pälsklädda vän',
    price: 5.99,
    image: '/image/husdjursleksak.jpg',
    category_id: 9,
  },
  {
    name: 'Bok: Bästsäljare',
    description: 'En bästsäljande bok för bokälskare',
    price: 12.99,
    image: '/image/bok.jpg',
    category_id: 10,
  },
  {
    name: 'Shampo',
    description: 'Mild och vårdande schampo för alla hårtyper',
    price: 6.49,
    image: '/image/shampo.jpg',
    category_id: 5,
  },
  {
    name: 'Proteindrink',
    description: 'Högkvalitativ proteindrink för träning',
    price: 15.99,
    image: '/image/proteindrink.jpg',
    category_id: 4,
  },
  {
    name: 'Nötblandning',
    description: 'En utsökt blandning av nötter och torkad frukt',
    price: 4.99,
    image: '/image/notterblandning.jpg',
    category_id: 3,
  },
  {
    name: 'Vitaminvatten',
    description: 'Hälsosamt vitaminberikat vatten',
    price: 2.49,
    image: '/image/vitaminvatten.jpg',
    category_id: 2,
  },
  {
    name: 'Kaffe',
    description: 'Premiumkaffe från kända kaffebönor',
    price: 7.99,
    image: '/image/kaffe.jpg',
    category_id: 1,
  },
  {
    name: 'Tomatsås',
    description: 'Hemlagad tomatsås av hög kvalitet',
    price: 3.99,
    image: '/image/tomatsas.jpg',
    category_id: 1,
  },
  {
    name: 'Energidryck',
    description: 'Energidryck med extra kick',
    price: 2.79,
    image: '/image/energidryck.jpg',
    category_id: 2,
  },
  {
    name: 'Chokladkakor',
    description: 'Mumsiga chokladkakor för sötsugna',
    price: 4.49,
    image: '/image/chokladkakor.jpg',
    category_id: 3,
  },
  {
    name: 'Vitamintillskott',
    description: 'Vitamintillskott för daglig hälsa',
    price: 9.99,
    image: '/image/vitamintillskott.jpg',
    category_id: 4,
  },
  {
    name: 'Tvättmedel',
    description: 'Effektivt tvättmedel för rena kläder',
    price: 5.29,
    image: '/image/tvattmedel.jpg',
    category_id: 8,
  },
  {
    name: 'Risottoris',
    description: 'Premiumrisottoris för gourmetmatlagning',
    price: 6.99,
    image: '/image/risottoris.jpg',
    category_id: 1,
  },
  {
    name: 'Fruktjuice',
    description: 'Färskpressad fruktjuice för en hälsosam start på dagen',
    price: 3.49,
    image: '/image/fruktjuice.jpg',
    category_id: 2,
  },
  {
    name: 'Chips',
    description: 'Krispiga och smakrika chips för snacksätare',
    price: 2.99,
    image: '/image/chips.jpg',
    category_id: 3,
  },
  {
    name: 'Proteinbar',
    description: 'Proteinbar för snabb och bekväm energi',
    price: 1.99,
    image: '/image/proteinbar.jpg',
    category_id: 4,
  },
  {
    name: 'Tandborste',
    description: 'Mjuk tandborste för daglig tandvård',
    price: 1.29,
    image: '/image/tandborste.jpg',
    category_id: 5,
  },
  {
    name: 'Hamburgare',
    description: 'Färdiga hamburgare för en enkel måltid',
    price: 7.49,
    image: '/image/hamburgare.jpg',
    category_id: 6,
  },
  {
    name: 'Barnkläder',
    description: 'Söta barnkläder i olika storlekar och färger',
    price: 12.99,
    image: '/image/barnklader.jpg',
    category_id: 7,
  },
  {
    name: 'Diskmedel',
    description: 'Effektivt diskmedel för glänsande rena tallrikar',
    price: 2.79,
    image: '/image/diskmedel.jpg',
    category_id: 8,
  },
  {
    name: 'Hundmat',
    description: 'Näringsrik hundmat för ditt fyrbenta sällskap',
    price: 6.99,
    image: '/image/hundmat.jpg',
    category_id: 9,
  },
  {
    name: 'Leksakspussel',
    description: 'Roligt leksakspussel för barn',
    price: 4.99,
    image: '/image/leksakspussel.jpg',
    category_id: 10,
  },  
  {
    name: 'Ekologiskt kaffe',
    description: 'Högkvalitativt ekologiskt kaffe från rättvis handel',
    price: 10.49,
    image: '/image/ekologiskt_kaffe.jpg',
    category_id: 1,
  },
  {
    name: 'Läskedryck',
    description: 'Förfriskande läskedryck i olika smaker',
    price: 1.99,
    image: '/image/laskedryck.jpg',
    category_id: 2,
  },
  {
    name: 'Popcorn',
    description: 'Krispiga popcorn för biokvällar',
    price: 3.79,
    image: '/image/popcorn.jpg',
    category_id: 3,
  },
  {
    name: 'Energibar',
    description: 'Energibar med naturliga ingredienser',
    price: 2.49,
    image: '/image/energibar.jpg',
    category_id: 4,
  },
  {
    name: 'Tandtråd',
    description: 'Tandtråd för optimal tandvård',
    price: 0.99,
    image: '/image/tandtrad.jpg',
    category_id: 5,
  },
  {
    name: 'Färskt bröd',
    description: 'Nybakat bröd för frukost och mellanmål',
    price: 4.29,
    image: '/image/farskt_brod.jpg',
    category_id: 6,
  },
  {
    name: 'Barnvagnar',
    description: 'Bekväma och säkra barnvagnar för småbarn',
    price: 149.99,
    image: '/image/barnvagnar.jpg',
    category_id: 7,
  },
  {
    name: 'Badrumsrengöring',
    description: 'Effektiv rengöring för badrummet',
    price: 3.29,
    image: '/image/badrumsrengoring.jpg',
    category_id: 8,
  },
  {
    name: 'Kattmat',
    description: 'Smaklig kattmat för din kattkamrat',
    price: 4.99,
    image: '/image/kattmat.jpg',
    category_id: 9,
  },
  {
    name: 'Legosats',
    description: 'Kreativt legosats för barn och vuxna',
    price: 24.99,
    image: '/image/legosats.jpg',
    category_id: 10,
  },
  {
    name: 'Olivolja',
    description: 'Kallpressad ekologisk olivolja',
    price: 7.99,
    image: '/image/olivolja.jpg',
    category_id: 1,
  },
  {
    name: 'Fruktsmoothie',
    description: 'Färsk fruktsmoothie för en hälsosam start på dagen',
    price: 3.99,
    image: '/image/fruktsmoothie.jpg',
    category_id: 2,
  },
  {
    name: 'Pretzel-snacks',
    description: 'Krispiga pretzel-snacks för knaprig njutning',
    price: 2.79,
    image: '/image/pretzel-snacks.jpg',
    category_id: 3,
  },
  {
    name: 'Vitaminpiller',
    description: 'Multivitamintillskott i pilleform',
    price: 8.49,
    image: '/image/vitaminpiller.jpg',
    category_id: 4,
  },
  {
    name: 'Hårtork',
    description: 'Kraftfull hårtork för snabb styling',
    price: 19.99,
    image: '/image/hartork.jpg',
    category_id: 5,
  },
  {
    name: 'Senap',
    description: 'Äkta senap gjord på ekologiska senapsfrön',
    price: 19.99,
    image: '/image/senap.jpg',
    category_id: 1,
  } 
];

module.exports = {
  products,
  categories,
};